/**
 * Content Generation Worker — สร้างเนื้อหาด้วย AI
 */
const WordPressClient = require('../services/wp-client');
const aiClient = require('../services/ai-client');
const db = require('../db');

module.exports = async function processContentGen(job) {
  const { customerId, topic, keywords, tone, length, language, featuredImage } = job.data;
  const customer = db.getCustomer(customerId);
  if (!customer) throw new Error(`Customer ${customerId} not found`);

  const wp = new WordPressClient({ siteUrl: customer.site_url, apiKey: customer.wp_api_key });

  db.addLog({ customerId, level: 'info', message: `Generating content: "${topic}"`, metadata: { jobId: job.id } });

  // 1. AI สร้างเนื้อหา
  const content = await aiClient.generateContent({ topic, keywords, tone, length, language });

  // 2. สร้าง Featured Image (ถ้ามี)
  let featuredMediaId = 0;
  if (featuredImage) {
    try {
      // Try to generate image via Module API
      
      const imgRes = await fetch(`${require('../config').moduleApi.url}/api/wordpress/v1/media/generate-image`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: topic, style: tone || 'professional' }),
        signal: AbortSignal.timeout(60000),
      });
      if (imgRes.ok) {
        const imgData = await imgRes.json();
        if (imgData.url) {
          const media = await wp.uploadMedia(imgData.url);
          featuredMediaId = media.id || 0;
        }
      }
    } catch (e) {
      db.addLog({ customerId, level: 'warn', message: `Featured image failed: ${e.message}`, metadata: { jobId: job.id } });
    }
  }

  // 3. สร้าง Post
  try {
    const post = await wp.createPost({
      title: content.title || topic,
      content: content.content || '<p>Content generated by WPilot</p>',
      status: 'draft',
      featuredMedia: featuredMediaId,
    });
    db.addLog({ customerId, level: 'info', message: `✅ Post created: "${post.title?.rendered || content.title}"`, metadata: { jobId: job.id, postId: post.id } });
    return { success: true, postId: post.id, postUrl: post.link };
  } catch (e) {
    db.addLog({ customerId, level: 'error', message: `❌ Post creation failed: ${e.message}`, metadata: { jobId: job.id } });
    throw e;
  }
};
